# Generated by Django 2.0.4 on 2018-07-05 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba', '0002_auto_20180705_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
