# Generated by Django 2.0.4 on 2018-07-08 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba', '0008_player_ppg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='ppg',
        ),
        migrations.AddField(
            model_name='player',
            name='assists',
            field=models.FloatField(default=0, max_length=3),
        ),
        migrations.AddField(
            model_name='player',
            name='defreb',
            field=models.FloatField(default=0, max_length=3),
        ),
        migrations.AddField(
            model_name='player',
            name='ofreb',
            field=models.FloatField(default=0, max_length=3),
        ),
        migrations.AddField(
            model_name='player',
            name='points',
            field=models.FloatField(default=0, max_length=3),
        ),
        migrations.AddField(
            model_name='player',
            name='steals',
            field=models.FloatField(default=0, max_length=3),
        ),
    ]
