# Generated by Django 2.0.4 on 2018-07-19 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba', '0009_auto_20180708_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='pos',
            field=models.CharField(default='null', max_length=5),
        ),
    ]
