# Generated by Django 2.0.4 on 2018-07-20 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba', '0010_player_pos'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='height',
            field=models.CharField(default='null', max_length=4),
        ),
        migrations.AddField(
            model_name='player',
            name='weight',
            field=models.FloatField(default=0, max_length=3),
        ),
    ]
