# Generated by Django 2.0.4 on 2018-07-23 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba', '0011_auto_20180720_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='fpoints',
            field=models.FloatField(default=0, max_length=3),
        ),
    ]
