# Generated by Django 2.0.4 on 2018-07-23 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba', '0012_player_fpoints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='fpoints',
            field=models.FloatField(default=models.FloatField(default=0, max_length=3), max_length=3),
        ),
    ]
