# Generated by Django 2.0.4 on 2018-07-23 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba', '0013_auto_20180723_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='fpoints',
            field=models.FloatField(default=0, max_length=3),
        ),
    ]
